
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gauri
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel LName = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        javax.swing.JLabel LEmpID = new javax.swing.JLabel();
        TxtEmpID = new javax.swing.JTextField();
        javax.swing.JLabel LAge = new javax.swing.JLabel();
        TxtAge = new javax.swing.JTextField();
        javax.swing.JLabel LGender = new javax.swing.JLabel();
        TxtGender = new javax.swing.JComboBox<>();
        javax.swing.JLabel LStartDate = new javax.swing.JLabel();
        TxtStartDate = new javax.swing.JTextField();
        javax.swing.JLabel LLevel = new javax.swing.JLabel();
        TxtLevel = new javax.swing.JComboBox<>();
        javax.swing.JLabel LTeamInfo = new javax.swing.JLabel();
        TxtTeamInfo = new javax.swing.JTextField();
        javax.swing.JLabel LPosition = new javax.swing.JLabel();
        TxtPosition = new javax.swing.JTextField();
        javax.swing.JLabel LCellPhone = new javax.swing.JLabel();
        TxtCellPhone = new javax.swing.JTextField();
        javax.swing.JLabel LEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        BtnBrowse = new javax.swing.JButton();
        javax.swing.JButton BtnDelete = new javax.swing.JButton();
        javax.swing.JScrollPane TEmp = new javax.swing.JScrollPane();
        TableEmp = new javax.swing.JTable();
        TxtImageFile = new javax.swing.JTextField();
        javax.swing.JButton BtnCreate = new javax.swing.JButton();
        javax.swing.JButton BtnUpdate = new javax.swing.JButton();
        LSearch = new javax.swing.JLabel();
        TxtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee List");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Profile"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setOpaque(false);

        LName.setText("Name");

        LEmpID.setText("EmployeeID");

        LAge.setText("Age");

        LGender.setText("Gender");

        TxtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other" }));

        LStartDate.setText("StartDate");

        LLevel.setText("Level");

        TxtLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        LTeamInfo.setText("TeamInfo");

        LPosition.setText("Position Title");

        LCellPhone.setText("Cell Phone No");

        LEmail.setText("Email");

        BtnBrowse.setText("Browse Image");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtName)
                    .addComponent(LEmpID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtEmpID)
                    .addComponent(LAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtAge)
                    .addComponent(LGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtStartDate)
                    .addComponent(LLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTeamInfo)
                    .addComponent(TxtPosition)
                    .addComponent(LCellPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtCellPhone)
                    .addComponent(LEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtEmail)
                    .addComponent(LPosition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LEmpID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LStartDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTeamInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LPosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LCellPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBrowse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        TableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "EmpID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell No", "Email"
            }
        ));
        TEmp.setViewportView(TableEmp);

        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        LSearch.setText("Search");

        TxtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtSearchMouseClicked(evt);
            }
        });
        TxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxtImageFile, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnCreate)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnUpdate))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(LSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDelete)
                            .addComponent(LSearch)
                            .addComponent(TxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtImageFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCreate)
                            .addComponent(BtnUpdate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        String Name = TxtName.getText();
        String Emp_Id = TxtEmpID.getText();
        String Age = TxtAge.getText();
        String Gender = TxtGender.getSelectedItem().toString();
        String StartDate = TxtStartDate.getText();
        String Level = TxtLevel.getSelectedItem().toString();
        String TeamInfo = TxtTeamInfo.getText();
        String PositionTitle = TxtPosition.getText();
        String PhoneNo = TxtCellPhone.getText();
        String Email = TxtEmail.getText();
        
        
        if (Name.isEmpty() || Emp_Id.isEmpty() || Age.isEmpty() || Gender.isEmpty() || StartDate.isEmpty() || Level.isEmpty()
                || TeamInfo.isEmpty() || PositionTitle.isEmpty() || PhoneNo.isEmpty() || Email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter All Fields", "Try again", JOptionPane.ERROR_MESSAGE);
        
        }
        else{
            DefaultTableModel Table1 = (DefaultTableModel) TableEmp.getModel();
            Table1.addRow(new Object[] {Name, Emp_Id, Age, Gender, StartDate, Level, TeamInfo,
                PositionTitle, PhoneNo, Email});
            
            TxtName.setText("");
            TxtEmpID.setText("");
            TxtAge.setText("");
            TxtGender.setSelectedIndex(0);
            TxtStartDate.setText("");
            TxtLevel.setSelectedIndex(0);
            TxtTeamInfo.setText("");
            TxtPosition.setText("");
            TxtCellPhone.setText("");
            TxtEmail.setText("");
            
        }
        
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        int row = TableEmp.getSelectedRow();
        
        if (row<0){
            JOptionPane.showMessageDialog(this, "No row is selected, please select a row", 
                    "Select Row", JOptionPane.ERROR_MESSAGE);
     
        }
        else { 
            DefaultTableModel Table1 = (DefaultTableModel) TableEmp.getModel();
            Table1.removeRow(row);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Table1 = (DefaultTableModel) TableEmp.getModel();
        if (TableEmp.getSelectedRowCount()==1){
           
            //updation for single row
            String Name = TxtName.getText();
            String Emp_ID = TxtEmpID.getText();
            String Age = TxtAge.getText();
            String Gender = TxtGender.getSelectedItem().toString();
            String StartDate = TxtStartDate.getText();
            String Level = TxtLevel.getSelectedItem().toString();
            String TeamInfo = TxtTeamInfo.getText();
            String PositionTitle = TxtPosition.getText();
            String PhoneNo = TxtCellPhone.getText();
            String Email= TxtEmail.getText();
            //String Image = image_txt.getText();
            
            //Update row from Table
            Table1.setValueAt(Name, TableEmp.getSelectedRow(),0);
            Table1.setValueAt(Emp_ID, TableEmp.getSelectedRow(),1);
            Table1.setValueAt(Age, TableEmp.getSelectedRow(),2);
            Table1.setValueAt(Gender, TableEmp.getSelectedRow(),3);
            Table1.setValueAt(StartDate, TableEmp.getSelectedRow(),4);
            Table1.setValueAt(Level, TableEmp.getSelectedRow(),5);
            Table1.setValueAt(TeamInfo, TableEmp.getSelectedRow(),6);
            Table1.setValueAt(PositionTitle, TableEmp.getSelectedRow(),7);
            Table1.setValueAt(PhoneNo, TableEmp.getSelectedRow(),8);
            Table1.setValueAt(Email, TableEmp.getSelectedRow(),9);
            //Table1.setValueAt(Image, TableEmp.getSelectedRow(),10);
            
            //message display for update
            JOptionPane.showMessageDialog(this, "Successfully Updated");
             } else{
            if(TableEmp.getRowCount()==0){
                //for Empty Table
                JOptionPane.showMessageDialog(this, "Empty Table");
            }else{
                //incase row is not selected or multiple selection
                JOptionPane.showMessageDialog(this, "Please select one row");
            }
        }
        TxtName.setText("");
        TxtEmpID.setText("");
        TxtAge.setText("");
        TxtGender.setSelectedIndex(0);
        TxtStartDate.setText("");
        TxtLevel.setSelectedIndex(0);
        TxtTeamInfo.setText("");
        TxtPosition.setText("");
        TxtCellPhone.setText("");
        TxtEmail.setText("");
        //Image_txt.setText("");
        
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void TxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSearchActionPerformed

    private void TxtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSearchMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBrowse;
    private javax.swing.JLabel LSearch;
    private javax.swing.JTable TableEmp;
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtCellPhone;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEmpID;
    private javax.swing.JComboBox<String> TxtGender;
    private javax.swing.JTextField TxtImageFile;
    private javax.swing.JComboBox<String> TxtLevel;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPosition;
    private javax.swing.JTextField TxtSearch;
    private javax.swing.JTextField TxtStartDate;
    private javax.swing.JTextField TxtTeamInfo;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
